// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

// https://stackoverflow.com/a/78627418
declare namespace JSX {
    type Element = HTMLElement;
    type AttributesToOverride = 'style';

    type CSSStyleDeclarationButMaybe = {
        [K in keyof CSSStyleDeclaration]?: CSSStyleDeclaration[K];
    };

    type HTMLAttributes<T extends HTMLElement> = {
        ref?: (element: T) => void;
        class?: string; // alias for className
        for?: string;   // alias for htmlFor
        //Define custom styles here
        style?: CSSStyleDeclarationButMaybe;

        [attr: `data-${string}`]: string | number | boolean | null | undefined;
        [attr: `aria-${string}`]: string | number | boolean | null | undefined;
    } & {
        [K in keyof Omit<T, AttributesToOverride>]?: T[K]; // <- Map directly to real DOM properties!
    };

    type ElementProps<T extends HTMLElement> = {
        [K in keyof T]: HTMLAttributes<T[K]>;
    };


    interface IntrinsicElements extends ElementProps<HTMLElementTagNameMapWithDocs> {

    }

    interface IntrinsicElements extends ElementProps<SVGElementTagNameMap> {

    }
}

interface HTMLElementTagNameMapWithDocs {
    /** @see {@link HTMLAnchorElement} */
    "a": HTMLAnchorElement;

    /** @see {@link HTMLElement} */
    "abbr": HTMLElement;

    /** @see {@link HTMLElement} */
    "address": HTMLElement;

    /** @see {@link HTMLAreaElement} */
    "area": HTMLAreaElement;

    /** @see {@link HTMLElement} */
    "article": HTMLElement;

    /** @see {@link HTMLElement} */
    "aside": HTMLElement;

    /** @see {@link HTMLAudioElement} */
    "audio": HTMLAudioElement;

    /** @see {@link HTMLElement} */
    "b": HTMLElement;

    /** @see {@link HTMLBaseElement} */
    "base": HTMLBaseElement;

    /** @see {@link HTMLElement} */
    "bdi": HTMLElement;

    /** @see {@link HTMLElement} */
    "bdo": HTMLElement;

    /** @see {@link HTMLQuoteElement} */
    "blockquote": HTMLQuoteElement;

    /** @see {@link HTMLBodyElement} */
    "body": HTMLBodyElement;

    /** @see {@link HTMLBRElement} */
    "br": HTMLBRElement;

    /** @see {@link HTMLButtonElement} */
    "button": HTMLButtonElement;

    /** @see {@link HTMLCanvasElement} */
    "canvas": HTMLCanvasElement;

    /** @see {@link HTMLTableCaptionElement} */
    "caption": HTMLTableCaptionElement;

    /** @see {@link HTMLElement} */
    "cite": HTMLElement;

    /** @see {@link HTMLElement} */
    "code": HTMLElement;

    /** @see {@link HTMLTableColElement} */
    "col": HTMLTableColElement;

    /** @see {@link HTMLTableColElement} */
    "colgroup": HTMLTableColElement;

    /** @see {@link HTMLDataElement} */
    "data": HTMLDataElement;

    /** @see {@link HTMLDataListElement} */
    "datalist": HTMLDataListElement;

    /** @see {@link HTMLElement} */
    "dd": HTMLElement;

    /** @see {@link HTMLModElement} */
    "del": HTMLModElement;

    /** @see {@link HTMLDetailsElement} */
    "details": HTMLDetailsElement;

    /** @see {@link HTMLElement} */
    "dfn": HTMLElement;

    /** @see {@link HTMLDialogElement} */
    "dialog": HTMLDialogElement;

    /** @see {@link HTMLDivElement} */
    "div": HTMLDivElement;

    /** @see {@link HTMLDListElement} */
    "dl": HTMLDListElement;

    /** @see {@link HTMLElement} */
    "dt": HTMLElement;

    /** @see {@link HTMLElement} */
    "em": HTMLElement;

    /** @see {@link HTMLEmbedElement} */
    "embed": HTMLEmbedElement;

    /** @see {@link HTMLFieldSetElement} */
    "fieldset": HTMLFieldSetElement;

    /** @see {@link HTMLElement} */
    "figcaption": HTMLElement;

    /** @see {@link HTMLElement} */
    "figure": HTMLElement;

    /** @see {@link HTMLElement} */
    "footer": HTMLElement;

    /** @see {@link HTMLFormElement} */
    "form": HTMLFormElement;

    /** @see {@link HTMLHeadingElement} */
    "h1": HTMLHeadingElement;

    /** @see {@link HTMLHeadingElement} */
    "h2": HTMLHeadingElement;

    /** @see {@link HTMLHeadingElement} */
    "h3": HTMLHeadingElement;

    /** @see {@link HTMLHeadingElement} */
    "h4": HTMLHeadingElement;

    /** @see {@link HTMLHeadingElement} */
    "h5": HTMLHeadingElement;

    /** @see {@link HTMLHeadingElement} */
    "h6": HTMLHeadingElement;

    /** @see {@link HTMLHeadElement} */
    "head": HTMLHeadElement;

    /** @see {@link HTMLElement} */
    "header": HTMLElement;

    /** @see {@link HTMLElement} */
    "hgroup": HTMLElement;

    /** @see {@link HTMLHRElement} */
    "hr": HTMLHRElement;

    /** @see {@link HTMLHtmlElement} */
    "html": HTMLHtmlElement;

    /** @see {@link HTMLElement} */
    "i": HTMLElement;

    /** @see {@link HTMLIFrameElement} */
    "iframe": HTMLIFrameElement;

    /** @see {@link HTMLImageElement} */
    "img": HTMLImageElement;

    /** @see {@link HTMLInputElement} */
    "input": HTMLInputElement;

    /** @see {@link HTMLModElement} */
    "ins": HTMLModElement;

    /** @see {@link HTMLElement} */
    "kbd": HTMLElement;

    /** @see {@link HTMLLabelElement} */
    "label": HTMLLabelElement;

    /** @see {@link HTMLLegendElement} */
    "legend": HTMLLegendElement;

    /** @see {@link HTMLLIElement} */
    "li": HTMLLIElement;

    /** @see {@link HTMLLinkElement} */
    "link": HTMLLinkElement;

    /** @see {@link HTMLElement} */
    "main": HTMLElement;

    /** @see {@link HTMLMapElement} */
    "map": HTMLMapElement;

    /** @see {@link HTMLElement} */
    "mark": HTMLElement;

    /** @see {@link HTMLMenuElement} */
    "menu": HTMLMenuElement;

    /** @see {@link HTMLMetaElement} */
    "meta": HTMLMetaElement;

    /** @see {@link HTMLMeterElement} */
    "meter": HTMLMeterElement;

    /** @see {@link HTMLElement} */
    "nav": HTMLElement;

    /** @see {@link HTMLElement} */
    "noscript": HTMLElement;

    /** @see {@link HTMLObjectElement} */
    "object": HTMLObjectElement;

    /** @see {@link HTMLOListElement} */
    "ol": HTMLOListElement;

    /** @see {@link HTMLOptGroupElement} */
    "optgroup": HTMLOptGroupElement;

    /** @see {@link HTMLOptionElement} */
    "option": HTMLOptionElement;

    /** @see {@link HTMLOutputElement} */
    "output": HTMLOutputElement;

    /** @see {@link HTMLParagraphElement} */
    "p": HTMLParagraphElement;

    /** @see {@link HTMLPictureElement} */
    "picture": HTMLPictureElement;

    /** @see {@link HTMLPreElement} */
    "pre": HTMLPreElement;

    /** @see {@link HTMLProgressElement} */
    "progress": HTMLProgressElement;

    /** @see {@link HTMLQuoteElement} */
    "q": HTMLQuoteElement;

    /** @see {@link HTMLElement} */
    "rp": HTMLElement;

    /** @see {@link HTMLElement} */
    "rt": HTMLElement;

    /** @see {@link HTMLElement} */
    "ruby": HTMLElement;

    /** @see {@link HTMLElement} */
    "s": HTMLElement;

    /** @see {@link HTMLElement} */
    "samp": HTMLElement;

    /** @see {@link HTMLScriptElement} */
    "script": HTMLScriptElement;

    /** @see {@link HTMLElement} */
    "search": HTMLElement;

    /** @see {@link HTMLElement} */
    "section": HTMLElement;

    /** @see {@link HTMLSelectElement} */
    "select": HTMLSelectElement;

    /** @see {@link HTMLSlotElement} */
    "slot": HTMLSlotElement;

    /** @see {@link HTMLElement} */
    "small": HTMLElement;

    /** @see {@link HTMLSourceElement} */
    "source": HTMLSourceElement;

    /** @see {@link HTMLSpanElement} */
    "span": HTMLSpanElement;

    /** @see {@link HTMLElement} */
    "strong": HTMLElement;

    /** @see {@link HTMLStyleElement} */
    "style": HTMLStyleElement;

    /** @see {@link HTMLElement} */
    "sub": HTMLElement;

    /** @see {@link HTMLElement} */
    "summary": HTMLElement;

    /** @see {@link HTMLElement} */
    "sup": HTMLElement;

    /** @see {@link HTMLTableElement} */
    "table": HTMLTableElement;

    /** @see {@link HTMLTableSectionElement} */
    "tbody": HTMLTableSectionElement;

    /** @see {@link HTMLTableCellElement} */
    "td": HTMLTableCellElement;

    /** @see {@link HTMLTemplateElement} */
    "template": HTMLTemplateElement;

    /** @see {@link HTMLTextAreaElement} */
    "textarea": HTMLTextAreaElement;

    /** @see {@link HTMLTableSectionElement} */
    "tfoot": HTMLTableSectionElement;

    /** @see {@link HTMLTableCellElement} */
    "th": HTMLTableCellElement;

    /** @see {@link HTMLTableSectionElement} */
    "thead": HTMLTableSectionElement;

    /** @see {@link HTMLTimeElement} */
    "time": HTMLTimeElement;

    /** @see {@link HTMLTitleElement} */
    "title": HTMLTitleElement;

    /** @see {@link HTMLTableRowElement} */
    "tr": HTMLTableRowElement;

    /** @see {@link HTMLTrackElement} */
    "track": HTMLTrackElement;

    /** @see {@link HTMLElement} */
    "u": HTMLElement;

    /** @see {@link HTMLUListElement} */
    "ul": HTMLUListElement;

    /** @see {@link HTMLElement} */
    "var": HTMLElement;

    /** @see {@link HTMLVideoElement} */
    "video": HTMLVideoElement;

    /** @see {@link HTMLElement} */
    "wbr": HTMLElement;
}


